SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
LEFT OUTER JOIN (
                 SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
                 FROM ECOLI_DATA
                 GROUP BY YEAR
                ) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR(A.DIFFERENTIATION_DATE), YEAR_DEV;
