SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '____-03-__' AND GENDER='W' AND TLNO NOT IN ('NULL')
ORDER BY MEMBER_ID;

/* 두 번째 풀이
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH)=3 AND GENDER='W' AND TLNO IS NOT NULL -- MONTH(속성) : 속성에서 '월'만 추출. YEAR(속성), DATE(속성)도 가능?
ORDER BY MEMBER_ID;
*/
