SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM((C.SALES * A.PRICE)) AS TOTAL_SALES
FROM BOOK AS A, AUTHOR AS B, (
                              SELECT BOOK_ID, SUM(SALES) AS SALES
                              FROM BOOK_SALES
                              WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') IN ('2022-01')
                              GROUP BY BOOK_ID
                             ) AS C
WHERE A.BOOK_ID = C.BOOK_ID
AND A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;
