SELECT ID, IFNULL(A.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA
LEFT OUTER JOIN (
                 SELECT PARENT_ID, COUNT(*) CHILD_COUNT
                 FROM ECOLI_DATA
                 WHERE PARENT_ID IS NOT NULL
                 GROUP BY PARENT_ID
                ) AS A
ON ID = A.PARENT_ID
ORDER BY ID;
