WITH RECURSIVE PARENT AS ( -- 재귀적인 테이블 PARENT 생성
  
    -- 반복되지 않는 구문에서 새로운 레이블 GENERATION 선언
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL -- 초기 세대 값을 1로 설정

    UNION -- 중복을 포함하지 않는 합집합

    -- 반복되는 구문에서 GENERATION을 1씩 추가한다
    SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA CHILD, PARENT
    WHERE PARENT.ID = CHILD.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GENERATION -- 결과 테이블 생성
FROM PARENT
WHERE ID NOT IN (SELECT IFNULL(PARENT_ID, 0) -- PARENT_ID가 NULL이 아닌 행의 ID
                 FROM ECOLI_DATA
                )
GROUP BY GENERATION
ORDER BY GENERATION;
