SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO LEFT JOIN REST_REVIEW
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE REST_INFO.ADDRESS LIKE '서울%'
AND REST_REVIEW.REVIEW_SCORE IS NOT NULL -- 리뷰가 없는 식당은 왜 제외를 해야하는지 의문. 문제 조건이 불분명함
GROUP BY REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS
ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC;

-- SELECT 절에서는 GROUP BY에서 사용한 속성과 집계 함수만 나올 수 있다
