SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS b, USED_GOODS_REPLY AS r
WHERE b.BOARD_ID = r.BOARD_ID
AND b.CREATED_DATE LIKE '2022-10%'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;
