SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-- UNION : 레이블이 겹치지 않게 집합(일반적인 합집합)
-- UNION ALL : 레이블이 겹치게 집합(교집합이 중복 출력되는 합집합)

-- NULL 속성 : 해당 속성의 모든 값을 NULL로 표시

-- NULL, IS NULL, IS NOT NULL, IFNULL 구분하기
-- NULL 속성 / IFNULL(속성,'속성의 값이 NULL일때 대체할 값') / IS NULL, IS NOT NULL : NULL인 것, NULL이 아닌 것 구분. WHERE 절(조건)에서 사용
